// ==UserScript==
// @name         Axiom
// @namespace    https://github.com/axiom/axiom
// @version      0.1.0
// @description  Tab-based scripting console for zombs.io — built on ZOUI
// @author       you
// @match        *://zombs.io/*
// @match        *://*.zombs.io/*
// @require      https://raw.githubusercontent.com/TropicalBanana2/ZOUI/refs/heads/main/zoui.js
// @grant        none
// @run-at       document-idle
// @updateURL    http://localhost:5173/axiom.user.js
// @downloadURL  http://localhost:5173/axiom.user.js
// ==/UserScript==

/*
 * Axiom — zombs.io scripting console
 *
 * Single-file Tampermonkey/Violentmonkey userscript. The same code is
 * generated by the editor's export feature; if you have the editor
 * running locally on http://localhost:5173, this script will pull
 * fresh builds via @updateURL.
 *
 * Architecture (all inline below to keep this a single file):
 *   THEME       — CSS variables + ZOUI theme object
 *   SCHEMA      — embedded UI tree + validators
 *   SCRIPT HOST — `ctx` + new Function('ctx', source) execution
 *   RENDERER    — schema → ZOUI components
 *   SHELL       — custom top-tab nav, bottom bar, console drawer
 *   BOOTSTRAP   — waits for ZOUI + host page, mounts shell
 */

(function () {
  "use strict";

  // ─── EMBEDDED SCHEMA ─────────────────────────────────────────────────
  // Regenerated by the editor on export. Edit by hand if you don't have
  // the editor installed — schemaVersion gates future migrations.
  // __AXIOM_SCHEMA_BEGIN__
  const SCHEMA = {
    "schemaVersion": 1,
    "meta": { "name": "Axiom", "version": "0.1.0", "hotkey": "`", "theme": "axiom-dark", "landingTabId": "home" },
    "tabs": [
      {
        "id": "home", "name": "Home", "icon": null,
        "sections": [
          {
            "id": "home-welcome", "name": "Welcome", "collapsible": false, "defaultOpen": true,
            "controls": [
              { "type": "text", "id": "home-welcome-blurb", "label": "",
                "defaultValue": "Axiom is a tab-based scripting console for zombs.io. Use the editor to add tabs, sections, and controls — each control can run a script you write. Press the hotkey (default backtick) to toggle this panel." },
              { "type": "button", "id": "home-welcome-hello", "label": "Say hello", "scriptId": "scr_hello", "secondary": false }
            ]
          },
          {
            "id": "home-quickref", "name": "Quick reference", "collapsible": true, "defaultOpen": false,
            "controls": [
              { "type": "text", "id": "home-quickref-blurb", "label": "",
                "defaultValue": "ctx.log(msg, level?) — write to the console panel.\nctx.game — read-only game state.\nctx.ui — read/set values of other controls by id.\nctx.storage — get/set persisted values.\nctx.on(event, fn) / ctx.off(event, fn) — lifecycle + tick hooks." }
            ]
          }
        ]
      },
      {
        "id": "demo", "name": "Demo", "icon": null,
        "sections": [
          {
            "id": "demo-controls", "name": "Every control type", "collapsible": false, "defaultOpen": true,
            "controls": [
              { "type": "toggle", "id": "demo-toggle", "label": "A toggle", "defaultValue": false, "scriptId": "scr_changed" },
              { "type": "slider", "id": "demo-slider", "label": "A slider", "defaultValue": 50, "min": 0, "max": 100, "step": 1, "scriptId": "scr_changed" },
              { "type": "input",  "id": "demo-text",   "label": "Some text", "defaultValue": "", "placeholder": "type something…", "scriptId": "scr_changed" },
              { "type": "number", "id": "demo-number", "label": "A number", "defaultValue": 1, "min": 0, "max": 999, "step": 1, "scriptId": "scr_changed" },
              { "type": "select", "id": "demo-select", "label": "A select", "defaultValue": "one",
                "options": [ { "value": "one", "label": "One" }, { "value": "two", "label": "Two" }, { "value": "three", "label": "Three" } ],
                "scriptId": "scr_changed" },
              { "type": "radio", "id": "demo-radio", "label": "A radio group", "defaultValue": "a",
                "options": [ { "value": "a", "label": "Alpha" }, { "value": "b", "label": "Beta" }, { "value": "c", "label": "Gamma" } ],
                "scriptId": "scr_changed" },
              { "type": "color",   "id": "demo-color",   "label": "A color",   "defaultValue": "#3b82f6", "scriptId": "scr_changed" },
              { "type": "keybind", "id": "demo-keybind", "label": "A keybind", "defaultValue": "K",        "scriptId": "scr_keybind" }
            ]
          }
        ]
      }
    ],
    "scripts": {
      "scr_hello":   { "id": "scr_hello",   "name": "Hello",        "source": "ctx.log('hello');" },
      "scr_changed": { "id": "scr_changed", "name": "Log changes",  "source": "// Runs whenever the bound control's value changes.\n// `value` is in scope as the new value, `controlId` as the id.\nctx.log(controlId + ' → ' + JSON.stringify(value));" },
      "scr_keybind": { "id": "scr_keybind", "name": "Log keypress", "source": "ctx.log('keybind pressed: ' + value);" }
    }
  };
  // __AXIOM_SCHEMA_END__

  // ─── THEME ───────────────────────────────────────────────────────────
  const AXIOM_PALETTE = {
    bgPrimary: "#0a0a0b", bgPanel: "#16161a", bgElevated: "#1c1c21",
    bgSearch: "#101013", bgRow: "rgba(255,255,255,0.02)", bgRowHover: "rgba(255,255,255,0.04)",
    border: "#26262c", borderStrong: "#33333a", divider: "rgba(255,255,255,0.06)",
    textPrimary: "#e4e4e7", textMuted: "#8b8b94", textDim: "#5c5c66",
    accent: "#3b82f6", accentHover: "#60a5fa",
    accentMuted: "rgba(59,130,246,0.12)", accentMuted2: "rgba(59,130,246,0.22)",
    accentText: "#93c5fd", accentGlow: "rgba(59,130,246,0.35)", accentOn: "#ffffff",
    success: "#22c55e", warning: "#f59e0b", error: "#ef4444",
    radius: "6px", radiusLg: "10px", shadow: "0 12px 40px rgba(0,0,0,0.55)",
    switchOff: "#3a3a42", switchOn: "#3b82f6", track: "#2a2a30",
  };
  const AXIOM_THEME_NAME = "axiom-dark";

  function axiomCssVars(p) { p = p || AXIOM_PALETTE; return `
:root, .axiom-root {
  --bg-primary:${p.bgPrimary}; --bg-panel:${p.bgPanel}; --bg-elevated:${p.bgElevated};
  --bg-search:${p.bgSearch}; --bg-row:${p.bgRow}; --bg-row-hover:${p.bgRowHover};
  --border:${p.border}; --border-strong:${p.borderStrong}; --divider:${p.divider};
  --text-primary:${p.textPrimary}; --text-muted:${p.textMuted}; --text-dim:${p.textDim};
  --accent:${p.accent}; --accent-hover:${p.accentHover};
  --accent-muted:${p.accentMuted}; --accent-muted-2:${p.accentMuted2};
  --accent-text:${p.accentText}; --accent-glow:${p.accentGlow}; --accent-on:${p.accentOn};
  --success:${p.success}; --warning:${p.warning}; --error:${p.error};
  --radius:${p.radius}; --radius-lg:${p.radiusLg}; --shadow:${p.shadow};
}`.trim(); }

  function axiomZouiTheme(p) { p = p || AXIOM_PALETTE; return {
    shadow: p.shadow, bg: p.bgPanel, bgHeader: p.bgPrimary, bgSearch: p.bgSearch,
    bgInput: p.bgElevated, bgRow: p.bgRow, bgRowHover: p.bgRowHover,
    bgTabHover: "rgba(255,255,255,0.04)",
    border: p.border, borderStrong: p.borderStrong, divider: p.divider,
    accent: p.accent, accentHover: p.accentHover,
    accentMuted: p.accentMuted, accentMuted2: p.accentMuted2,
    accentText: p.accentText, accentGlow: p.accentGlow,
    text1: p.textPrimary, text2: p.textMuted, text3: p.textDim, textOnAccent: p.accentOn,
    success: p.success, warning: p.warning, error: p.error,
    switchOff: p.switchOff, switchOn: p.switchOn, track: p.track,
    radius: p.radius, radiusLg: p.radiusLg,
  }; }

  // ─── SCHEMA HELPERS ──────────────────────────────────────────────────
  function findControl(schema, controlId) {
    for (let i = 0; i < schema.tabs.length; i++) {
      const tab = schema.tabs[i];
      for (let j = 0; j < tab.sections.length; j++) {
        const sec = tab.sections[j];
        for (let k = 0; k < sec.controls.length; k++) {
          if (sec.controls[k].id === controlId)
            return { tab: tab, section: sec, control: sec.controls[k], indices: [i, j, k] };
        }
      }
    }
    return null;
  }

  // ─── SCRIPT HOST ─────────────────────────────────────────────────────
  function createScriptHost(deps) {
    const ui = deps.ui, axiom = deps.axiom, schema = deps.schema;
    const compiled = new Map();

    function compile(scriptId, source, extraNames) {
      const cacheKey = scriptId + "::" + extraNames.join(",") + "::" + source;
      if (compiled.has(cacheKey)) return compiled.get(cacheKey);
      let fn;
      try { fn = new Function("ctx", ...extraNames, source); }
      catch (err) {
        const message = err && err.message ? err.message : String(err);
        fn = function () { throw new Error("Syntax error: " + message); };
      }
      compiled.set(cacheKey, fn);
      return fn;
    }

    const gameProxy = new Proxy({}, {
      get: function (_t, prop) {
        try {
          const w = typeof window !== "undefined" ? window : globalThis;
          if (prop === "window") return w;
          return w[prop];
        } catch (_) { return undefined; }
      }
    });

    const uiCtx = {
      getValue: function (controlId) { return axiom.values[controlId]; },
      setValue: function (controlId, value) {
        const found = findControl(schema, controlId);
        if (!found) return false;
        axiom.values[controlId] = value;
        axiom.cache.set("v::" + controlId, value);
        const updater = axiom.controlUpdaters.get(controlId);
        if (updater) try { updater(value); } catch (_) {}
        return true;
      },
      trigger: function (controlId) {
        const found = findControl(schema, controlId);
        if (!found) return false;
        const c = found.control;
        if (!c.scriptId) return false;
        const extras = c.type === "button"
          ? { controlId: c.id }
          : { controlId: c.id, value: axiom.values[c.id] };
        run(c.scriptId, extras);
        return true;
      },
    };

    const storageCtx = {
      get: function (key, fallback) { return axiom.cache.get("s::" + key, fallback); },
      set: function (key, value) { axiom.cache.set("s::" + key, value); },
      delete: function (key) { return axiom.cache.delete("s::" + key); },
    };

    function logCtx(message, level) {
      axiom.console.write(level || "log", message);
    }

    const ctx = {
      get game() { return gameProxy; },
      ui: uiCtx, storage: storageCtx, log: logCtx,
      on: function (event, handler) { return ui.on(event, handler); },
      off: function (event, handler) { return ui.off(event, handler); },
      toast: function (msg, type, duration) { ui.toast(msg, type || "info", duration || 2400); },
    };

    function run(scriptId, extras) {
      extras = extras || {};
      const script = schema.scripts[scriptId];
      if (!script) {
        axiom.console.write("error", "[script] " + scriptId + " — not found");
        return undefined;
      }
      const names = Object.keys(extras);
      const fn = compile(scriptId, script.source, names);
      try {
        return fn(ctx, ...names.map(function (n) { return extras[n]; }));
      } catch (err) {
        const where = extras.controlId ? " (control: " + extras.controlId + ")" : "";
        const msg = err && err.message ? err.message : String(err);
        axiom.console.write("error", "[script " + scriptId + where + "] " + msg);
        return undefined;
      }
    }

    function evalShowIf(scriptId, controlId) {
      const v = run(scriptId, { controlId: controlId });
      return v === undefined ? true : Boolean(v);
    }

    return { ctx: ctx, run: run, evalShowIf: evalShowIf };
  }

  // ─── RENDERER ────────────────────────────────────────────────────────
  function renderSchema(deps) {
    const ui = deps.ui, axiom = deps.axiom, schema = deps.schema, scriptHost = deps.scriptHost;
    resetPanel(ui);
    axiom.values = {};
    axiom.controlUpdaters = new Map();
    for (const tab of schema.tabs) {
      const tabName = ui.addTab(tab.name, tab.icon || null);
      axiom.tabIds.set(tab.id, tabName);
      for (const section of tab.sections) {
        let parent = tabName;
        if (section.collapsible) {
          parent = ui.addCollapsible(tabName, section.name, !!section.defaultOpen, {
            persist: "__sec_" + section.id,
          });
        } else if (section.name) {
          ui.addHeader(tabName, section.name);
        }
        for (const control of section.controls) {
          renderControl({ ui: ui, axiom: axiom, schema: schema, scriptHost: scriptHost, parent: parent, control: control });
        }
      }
    }
    const landing = schema.meta && schema.meta.landingTabId;
    const landingName = landing && axiom.tabIds.get(landing);
    if (landingName) ui.switchTab(landingName);
  }

  function resetPanel(ui) {
    if (ui.sidebar) {
      const label = ui.sidebar.querySelector(".zui-sidebar-label");
      [...ui.sidebar.querySelectorAll(".zui-tab")].forEach(function (el) { el.remove(); });
      if (label) ui.sidebar.appendChild(label);
    }
    if (ui.content) ui.content.innerHTML = "";
    ui.tabs = {}; ui.activeTab = null;
    ui._cols = {}; ui._colTabMap = {}; ui.features = [];
  }

  function renderControl(deps) {
    const ui = deps.ui, axiom = deps.axiom, scriptHost = deps.scriptHost, parent = deps.parent, c = deps.control;
    const persist = "v::" + c.id;
    const opts = { persist: persist, tooltip: c.tooltip || undefined };
    if (c.showIfScriptId) opts.showIf = function () { return scriptHost.evalShowIf(c.showIfScriptId, c.id); };

    function fire(value) {
      if (c.scriptId) scriptHost.run(c.scriptId, { controlId: c.id, value: value });
      axiom.values[c.id] = value;
    }
    function readPersisted(key, fallback) {
      try { const v = ui._cache && ui._cache.get(key); return v === undefined ? fallback : v; }
      catch (_) { return fallback; }
    }

    switch (c.type) {
      case "text":
        ui.addText(parent, String(c.defaultValue != null ? c.defaultValue : (c.label || "")), false);
        break;
      case "button":
        ui.addButton(parent, c.label || "Button", function () {
          if (c.scriptId) scriptHost.run(c.scriptId, { controlId: c.id });
        }, !!c.secondary);
        break;
      case "toggle": {
        const def = !!c.defaultValue;
        ui.addToggle(parent, c.label || "Toggle", def, fire, opts);
        axiom.values[c.id] = readPersisted(persist, def);
        break;
      }
      case "slider": {
        const def = Number(c.defaultValue != null ? c.defaultValue : 0);
        ui.addSlider(parent, c.label || "Slider", Number(c.min || 0), Number(c.max || 100), def, fire, opts);
        axiom.values[c.id] = readPersisted(persist, def);
        break;
      }
      case "input": {
        const def = c.defaultValue != null ? c.defaultValue : "";
        ui.addTextbox(parent, c.label || "Text", c.placeholder || "", fire, def, opts);
        axiom.values[c.id] = readPersisted(persist, def);
        break;
      }
      case "number": {
        const def = Number(c.defaultValue != null ? c.defaultValue : 0);
        ui.addNumberInput(parent, c.label || "Number",
          Number(c.min || 0), Number(c.max || 100), Number(c.step || 1), def, fire, opts);
        axiom.values[c.id] = readPersisted(persist, def);
        break;
      }
      case "select": {
        const opt0 = (c.options && c.options[0]) || { value: "" };
        const def = c.defaultValue != null ? c.defaultValue : opt0.value;
        const options = (c.options || []).map(function (o) { return { value: o.value, label: o.label || o.value }; });
        ui.addSelect(parent, c.label || "Select", options, fire, opts);
        axiom.values[c.id] = readPersisted(persist, def);
        break;
      }
      case "radio": {
        const opt0 = (c.options && c.options[0]) || { value: "" };
        const def = c.defaultValue != null ? c.defaultValue : opt0.value;
        const options = (c.options || []).map(function (o) { return { value: o.value, label: o.label || o.value }; });
        ui.addRadioGroup(parent, c.label || "Radio", options, def, fire, opts);
        axiom.values[c.id] = readPersisted(persist, def);
        break;
      }
      case "color": {
        const def = c.defaultValue || "#3b82f6";
        ui.addColorPicker(parent, c.label || "Color", def, fire, opts);
        axiom.values[c.id] = readPersisted(persist, def);
        break;
      }
      case "keybind": {
        const def = c.defaultValue || "K";
        ui.addKeybind(parent, c.label || "Keybind", def, fire, { ...opts, bind: true });
        axiom.values[c.id] = readPersisted(persist, def);
        break;
      }
      default:
        ui.addText(parent, "[unknown control type: " + c.type + "]", true);
    }
  }

  // ─── SHELL ───────────────────────────────────────────────────────────
  const SHELL_STYLE_ID = "axiom-shell-styles";
  const SHELL_CSS_VARS = "axiom-css-vars";

  function escapeHtml(s) {
    return String(s == null ? "" : s).replace(/[&<>"']/g, function (m) {
      return ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[m];
    });
  }

  function installStyles() {
    if (!document.getElementById(SHELL_CSS_VARS)) {
      const s = document.createElement("style");
      s.id = SHELL_CSS_VARS;
      s.textContent = axiomCssVars();
      document.head.appendChild(s);
    }
    if (document.getElementById(SHELL_STYLE_ID)) return;
    const s = document.createElement("style");
    s.id = SHELL_STYLE_ID;
    s.textContent = SHELL_CSS;
    document.head.appendChild(s);
  }

  const SHELL_CSS = `
    .axiom-root { position: relative; display: flex; flex-direction: column;
      width: 100%; height: 100%; font-family: -apple-system,"Segoe UI","Inter",sans-serif;
      color: var(--text-primary); background: var(--bg-primary);
      border: 1px solid var(--border); border-radius: var(--radius-lg);
      overflow: hidden; box-shadow: var(--shadow); }
    .axiom-topbar { display: flex; align-items: center; gap: 16px; padding: 8px 12px;
      background: var(--bg-primary); border-bottom: 1px solid var(--border); min-height: 44px; }
    .axiom-brand { display: flex; align-items: center; gap: 8px; }
    .axiom-brand-dot { width: 8px; height: 8px; border-radius: 50%; background: var(--accent); box-shadow: 0 0 8px var(--accent-glow); }
    .axiom-brand-name { font-weight: 600; font-size: 13px; letter-spacing: 0.02em; }
    .axiom-brand-version { font-size: 11px; color: var(--text-dim); }
    .axiom-tabs { display: flex; gap: 2px; flex: 1; overflow-x: auto; }
    .axiom-tab { background: transparent; border: 0; color: var(--text-muted);
      font-size: 12px; padding: 6px 12px; border-radius: var(--radius); cursor: pointer;
      transition: background 0.12s, color 0.12s; white-space: nowrap; font-family: inherit; }
    .axiom-tab:hover { background: var(--bg-row-hover); color: var(--text-primary); }
    .axiom-tab.active { background: var(--accent-muted); color: var(--accent-text);
      box-shadow: inset 0 -1px 0 var(--accent); }
    .axiom-actions { display: flex; gap: 4px; }
    .axiom-iconbtn { background: transparent; border: 1px solid transparent; color: var(--text-muted);
      width: 28px; height: 28px; border-radius: var(--radius); cursor: pointer; font-size: 13px;
      line-height: 1; display: inline-flex; align-items: center; justify-content: center;
      transition: background 0.12s, color 0.12s, border-color 0.12s; font-family: inherit; }
    .axiom-iconbtn:hover { background: var(--bg-elevated); color: var(--text-primary); border-color: var(--border-strong); }
    .axiom-stage { flex: 1; overflow: hidden; position: relative; background: var(--bg-primary); }
    .axiom-zoui-mount { width: 100%; height: 100%; }
    .axiom-zoui-mount .zui-headerbar,
    .axiom-zoui-mount .zui-sidebar,
    .axiom-zoui-mount .zui-resize-handle { display: none !important; }
    .axiom-zoui-mount .zui-wrapper { width: 100% !important; height: 100% !important;
      background: transparent !important; border: 0 !important; box-shadow: none !important; }
    .axiom-zoui-mount .zui-body { width: 100% !important; height: 100% !important; }
    .axiom-zoui-mount .zui-content { flex: 1; width: 100%; padding: 12px 16px; background: var(--bg-primary); }
    .axiom-zoui-mount .zui-global-search { background: var(--bg-search); border-bottom: 1px solid var(--border); }
    .axiom-bottombar { display: flex; align-items: center; gap: 8px; padding: 6px 12px;
      min-height: 28px; background: var(--bg-panel); border-top: 1px solid var(--border);
      font-size: 11px; color: var(--text-muted); }
    .axiom-status { font-size: 9px; }
    .axiom-status[data-status="idle"]    { color: var(--text-dim); }
    .axiom-status[data-status="active"]  { color: var(--accent); }
    .axiom-status[data-status="warning"] { color: var(--warning); }
    .axiom-status[data-status="error"]   { color: var(--error); }
    .axiom-bottombar-spacer { flex: 1; }
    .axiom-hint kbd { background: var(--bg-elevated); border: 1px solid var(--border-strong);
      border-radius: 3px; padding: 0 4px; font-family: ui-monospace, monospace; font-size: 10px; color: var(--text-primary); }
    .axiom-console { position: absolute; left: 0; right: 0; bottom: 0;
      background: var(--bg-elevated); border-top: 1px solid var(--border-strong);
      max-height: 38%; display: flex; flex-direction: column;
      transform: translateY(100%); transition: transform 0.18s ease; z-index: 5; }
    .axiom-console[data-open="true"] { transform: translateY(0); }
    .axiom-console-header { display: flex; align-items: center; justify-content: space-between;
      padding: 6px 12px; background: var(--bg-panel); border-bottom: 1px solid var(--border);
      font-size: 11px; color: var(--text-muted); text-transform: uppercase; letter-spacing: 0.05em; }
    .axiom-console-actions { display: flex; gap: 4px; }
    .axiom-console-actions .axiom-iconbtn { width: auto; padding: 0 8px; font-size: 11px; height: 22px; }
    .axiom-console-body { flex: 1; overflow-y: auto; padding: 6px 0;
      font-family: ui-monospace, "JetBrains Mono", "SF Mono", monospace; font-size: 12px; }
    .axiom-console-line { display: grid; grid-template-columns: 72px 56px 1fr; column-gap: 8px; padding: 2px 12px; }
    .axiom-console-line:hover { background: var(--bg-row-hover); }
    .axiom-console-time { color: var(--text-dim); }
    .axiom-console-level { color: var(--text-muted); text-transform: uppercase; font-size: 10px; align-self: center; }
    .axiom-console-line.lvl-error .axiom-console-level { color: var(--error); }
    .axiom-console-line.lvl-warn  .axiom-console-level { color: var(--warning); }
    .axiom-console-line.lvl-info  .axiom-console-level { color: var(--accent-text); }
    .axiom-console-msg { color: var(--text-primary); white-space: pre-wrap; word-break: break-word; }

    /* Floating host (used when #hud-menu-settings isn't present). */
    .axiom-host { position: fixed; top: 60px; right: 24px;
      width: 520px; height: 580px; z-index: 999998; background: transparent; }
    .axiom-host.is-minimized { width: auto; height: auto; }
    .axiom-root.is-minimized { height: auto; }
    .axiom-root.is-minimized .axiom-stage,
    .axiom-root.is-minimized .axiom-bottombar,
    .axiom-root.is-minimized .axiom-console { display: none; }
    .axiom-topbar { cursor: grab; }
    .axiom-topbar:active { cursor: grabbing; }
  `;

  function makeConsole(panel, body) {
    const lines = [];
    function fmtTime() {
      const d = new Date(), pad = function (n) { return String(n).padStart(2, "0"); };
      return pad(d.getHours()) + ":" + pad(d.getMinutes()) + ":" + pad(d.getSeconds());
    }
    function write(level, message) {
      const row = document.createElement("div");
      row.className = "axiom-console-line lvl-" + level;
      const text = typeof message === "string" ? message : safeStringify(message);
      row.innerHTML = '<span class="axiom-console-time">' + fmtTime() + '</span>' +
                      '<span class="axiom-console-level">' + level + '</span>' +
                      '<span class="axiom-console-msg"></span>';
      row.querySelector(".axiom-console-msg").textContent = text;
      body.appendChild(row);
      lines.push({ level: level, message: text, ts: Date.now() });
      body.scrollTop = body.scrollHeight;
      while (body.childNodes.length > 500) body.removeChild(body.firstChild);
      if (level === "error") open();
    }
    function open()   { panel.dataset.open = "true"; }
    function close()  { panel.dataset.open = "false"; }
    function toggle() { panel.dataset.open = panel.dataset.open === "true" ? "false" : "true"; }
    function clear()  { body.innerHTML = ""; lines.length = 0; }
    return { write: write, open: open, close: close, toggle: toggle, clear: clear, lines: lines };
  }
  function safeStringify(v) { try { return JSON.stringify(v); } catch (_) { return String(v); } }

  function buildShell(deps) {
    installStyles();
    const ZOUI = deps.ZOUI, container = deps.container, schema = deps.schema;
    const root = document.createElement("div");
    root.className = "axiom-root";
    root.innerHTML =
      '<div class="axiom-topbar">' +
        '<div class="axiom-brand">' +
          '<span class="axiom-brand-dot"></span>' +
          '<span class="axiom-brand-name">' + escapeHtml(schema.meta && schema.meta.name || "Axiom") + '</span>' +
          '<span class="axiom-brand-version">v' + escapeHtml(schema.meta && schema.meta.version || "") + '</span>' +
        '</div>' +
        '<nav class="axiom-tabs" role="tablist"></nav>' +
        '<div class="axiom-actions">' +
          '<button class="axiom-iconbtn" data-action="search" title="Search (Ctrl+F)">⌕</button>' +
          '<button class="axiom-iconbtn" data-action="console" title="Toggle console">≡</button>' +
          '<button class="axiom-iconbtn" data-action="minimize" title="Minimize">−</button>' +
        '</div>' +
      '</div>' +
      '<div class="axiom-stage"></div>' +
      '<div class="axiom-bottombar">' +
        '<span class="axiom-status" data-status="idle">●</span>' +
        '<span class="axiom-status-text">Ready</span>' +
        '<span class="axiom-bottombar-spacer"></span>' +
        '<span class="axiom-hint">Press <kbd>' + escapeHtml(schema.meta && schema.meta.hotkey || "`") + '</kbd> to toggle</span>' +
      '</div>' +
      '<div class="axiom-console" data-open="false">' +
        '<div class="axiom-console-header">' +
          '<span>Console</span>' +
          '<span class="axiom-console-actions">' +
            '<button data-console-action="clear" class="axiom-iconbtn">Clear</button>' +
            '<button data-console-action="close" class="axiom-iconbtn">×</button>' +
          '</span>' +
        '</div>' +
        '<div class="axiom-console-body"></div>' +
      '</div>';
    container.appendChild(root);
    const stage = root.querySelector(".axiom-stage");
    const zouiMount = document.createElement("div");
    zouiMount.className = "axiom-zoui-mount";
    stage.appendChild(zouiMount);

    ZOUI.registerTheme(AXIOM_THEME_NAME, axiomZouiTheme());
    const ui = new ZOUI(zouiMount, schema.meta && schema.meta.name || "Axiom",
                                   schema.meta && schema.meta.version || "0.1.0", { icon: "▲" });
    ui.setTheme(AXIOM_THEME_NAME);

    const consoleEl = root.querySelector(".axiom-console");
    const consoleBody = consoleEl.querySelector(".axiom-console-body");
    const consoleCtl = makeConsole(consoleEl, consoleBody);

    root.querySelector('[data-action="search"]').onclick   = function () { ui.searchInput && ui.searchInput.focus(); };
    root.querySelector('[data-action="console"]').onclick  = function () { consoleCtl.toggle(); };
    root.querySelector('[data-action="minimize"]').onclick = function () { ui.toggleMinimize(); };
    consoleEl.querySelector('[data-console-action="clear"]').onclick = function () { consoleCtl.clear(); };
    consoleEl.querySelector('[data-console-action="close"]').onclick = function () { consoleCtl.close(); };

    const tabBar = root.querySelector(".axiom-tabs");
    function projectTabs() {
      tabBar.innerHTML = "";
      const sidebarBtns = [...ui.sidebar.querySelectorAll(".zui-tab")];
      sidebarBtns.forEach(function (sb) {
        const name = sb.querySelector("span") ? sb.querySelector("span").textContent : "";
        const btn = document.createElement("button");
        btn.className = "axiom-tab";
        if (sb.classList.contains("active")) btn.classList.add("active");
        btn.textContent = name;
        btn.onclick = function () {
          ui.switchTab(name);
          [...tabBar.children].forEach(function (c) { c.classList.remove("active"); });
          btn.classList.add("active");
        };
        tabBar.appendChild(btn);
      });
    }
    const observer = new MutationObserver(projectTabs);
    observer.observe(ui.sidebar, { childList: true, subtree: false });

    const statusEl = root.querySelector(".axiom-status");
    const statusText = root.querySelector(".axiom-status-text");
    function setStatus(text, level) {
      statusText.textContent = text;
      statusEl.dataset.status = level || "idle";
    }

    function toggleMinimize() { root.classList.toggle("is-minimized"); }
    root.querySelector('[data-action="minimize"]').onclick = toggleMinimize;

    const hotkeyChord = parseChord(schema.meta && schema.meta.hotkey || "`");
    function onHotkey(e) {
      if (!matchChord(e, hotkeyChord)) return;
      const t = e.target;
      if (t && (t.tagName === "INPUT" || t.tagName === "TEXTAREA" || t.isContentEditable)) return;
      e.preventDefault();
      toggleMinimize();
    }
    window.addEventListener("keydown", onHotkey);

    const dragCleanup = enableDrag(root, container);

    return {
      ui: ui, root: root, tabBar: tabBar, syncTabs: projectTabs,
      setStatus: setStatus, toggleMinimize: toggleMinimize, console: consoleCtl,
      destroy: function () {
        observer.disconnect();
        window.removeEventListener("keydown", onHotkey);
        if (dragCleanup) dragCleanup();
        try { ui.destroy(); } catch (_) {}
        root.remove();
      },
    };
  }

  function enableDrag(root, host) {
    if (!host || !host.classList || !host.classList.contains("axiom-host")) return null;
    const topbar = root.querySelector(".axiom-topbar");
    let dragging = false, sx = 0, sy = 0, ox = 0, oy = 0;
    function down(e) {
      if (e.target.closest("button, input, select, .axiom-tab")) return;
      dragging = true; sx = e.clientX; sy = e.clientY;
      const r = host.getBoundingClientRect();
      ox = r.left; oy = r.top;
      document.body.style.userSelect = "none";
    }
    function move(e) {
      if (!dragging) return;
      host.style.left = (ox + e.clientX - sx) + "px";
      host.style.top  = (oy + e.clientY - sy) + "px";
      host.style.right = "auto";
    }
    function up() { dragging = false; document.body.style.userSelect = ""; }
    topbar.addEventListener("mousedown", down);
    window.addEventListener("mousemove", move);
    window.addEventListener("mouseup", up);
    return function () {
      topbar.removeEventListener("mousedown", down);
      window.removeEventListener("mousemove", move);
      window.removeEventListener("mouseup", up);
    };
  }

  function parseChord(combo) {
    const parts = String(combo).split("+").map(function (p) { return p.trim(); });
    const c = { ctrl: false, shift: false, alt: false, meta: false, key: "" };
    for (const p of parts) {
      const lower = p.toLowerCase();
      if (lower === "ctrl" || lower === "control") c.ctrl = true;
      else if (lower === "shift") c.shift = true;
      else if (lower === "alt" || lower === "option") c.alt = true;
      else if (lower === "meta" || lower === "cmd" || lower === "command") c.meta = true;
      else c.key = lower;
    }
    return c;
  }
  function matchChord(e, c) {
    if (!!e.ctrlKey  !== c.ctrl)  return false;
    if (!!e.shiftKey !== c.shift) return false;
    if (!!e.altKey   !== c.alt)   return false;
    if (!!e.metaKey  !== c.meta)  return false;
    return (e.key || "").toLowerCase() === c.key;
  }

  // ─── BOOTSTRAP ───────────────────────────────────────────────────────
  function waitFor(test, max) {
    return new Promise(function (resolve, reject) {
      const start = Date.now();
      (function tick() {
        try { const v = test(); if (v) return resolve(v); } catch (_) {}
        if (Date.now() - start > (max || 15000)) return reject(new Error("waitFor timed out"));
        setTimeout(tick, 100);
      })();
    });
  }

  // Live-reload over SSE. The userscript opens an EventSource against
  // the uiengine dev server; whenever the schema changes there, we
  // tear down the current shell and rebuild against the new schema.
  // No-op when no dev server is reachable.
  const DEV_SERVER = "http://localhost:5173";

  function connectLiveReload(onSchema, onStatus) {
    let es;
    let stopped = false;
    function open() {
      if (stopped) return;
      try {
        es = new EventSource(DEV_SERVER + "/__axiom/events");
      } catch (_) { return; }
      es.addEventListener("hello", function () { onStatus && onStatus("live"); });
      es.addEventListener("schema", function (evt) {
        try { onSchema(JSON.parse(evt.data)); } catch (_) {}
      });
      es.onerror = function () {
        // EventSource auto-reconnects, but on persistent failure we
        // surface "offline" so the user knows live-reload isn't active.
        onStatus && onStatus("offline");
      };
    }
    open();
    return function () { stopped = true; es && es.close(); };
  }

  async function start() {
    // Wait for ZOUI (loaded via @require) and a DOM body to attach to.
    await waitFor(function () { return typeof ZOUI !== "undefined" && document.body; });

    // Mount inside zombs.io's settings menu if present, else a floating
    // host container as a fallback.
    let host;
    const settingsHook = document.querySelector("#hud-menu-settings");
    if (settingsHook) {
      host = settingsHook;
    } else {
      host = document.createElement("div");
      host.className = "axiom-host";
      document.body.appendChild(host);
    }

    // `current` is the active shell/axiom bundle; `mount(schema)`
    // tears it down and rebuilds. Called once at boot and again on
    // every live-reload push.
    let current = null;
    function mount(schema) {
      // Preserve transient session state across rebuilds.
      const prevConsoleLines = current?.shell?.console?.lines?.slice() || [];
      const prevMinimized = current?.shell?.root?.classList?.contains("is-minimized");

      if (current) {
        try { current.shell.destroy(); } catch (_) {}
      }
      host.innerHTML = "";

      const shell = buildShell({ ZOUI: ZOUI, container: host, schema: schema });
      const axiom = {
        schema: schema, ui: shell.ui, cache: shell.ui._cache,
        console: shell.console, values: {},
        controlUpdaters: new Map(), tabIds: new Map(),
      };
      const scriptHost = createScriptHost({ ui: shell.ui, axiom: axiom, schema: schema });
      renderSchema({ ui: shell.ui, axiom: axiom, schema: schema, scriptHost: scriptHost });

      // Replay prior console lines so live-reload doesn't wipe context.
      prevConsoleLines.forEach(function (l) { shell.console.write(l.level, l.message); });
      if (prevMinimized) shell.root.classList.add("is-minimized");

      window.__axiom = { schema: schema, ui: shell.ui, shell: shell, axiom: axiom, scriptHost: scriptHost };
      current = { shell: shell, axiom: axiom, scriptHost: scriptHost };
      return current;
    }

    mount(SCHEMA);
    current.shell.console.write("info",
      "Axiom v" + (SCHEMA.meta && SCHEMA.meta.version) +
      " ready. Press " + (SCHEMA.meta && SCHEMA.meta.hotkey || "`") + " to toggle.");

    // Wire live-reload. Each schema push rebuilds the shell in place
    // and logs the swap. Status flips between "live" and "offline" in
    // the bottombar.
    connectLiveReload(
      function onSchema(newSchema) {
        mount(newSchema);
        current.shell.setStatus && current.shell.setStatus(
          "uiengine live · v" + (newSchema.meta && newSchema.meta.version || "?"), "active");
        current.shell.console.write("info",
          "[uiengine] reloaded schema (" + newSchema.tabs.length + " tabs, " +
          Object.keys(newSchema.scripts).length + " scripts)");
      },
      function onStatus(state) {
        if (!current) return;
        if (state === "live") current.shell.setStatus("uiengine live", "active");
        else if (state === "offline") current.shell.setStatus("uiengine offline", "idle");
      }
    );
  }

  start().catch(function (err) {
    console.error("[Axiom] failed to start:", err);
  });
})();
